language: elixir
elixir:
  - 1.0.0
  - 1.1.1
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - 18.0
  - 18.1
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, coveralls.travis"
